version: "3.9"
services:
  express:
    image: "ghcr.io/relaycc/robot/express:${GITHUB_SHA}"
    build:
      context: ".."
      dockerfile: "./deploy/Dockerfile.express"
    expose:
      - ${EXPRESS_PORT}
    environment:
      FRONT_API_KEY: ${FRONT_API_KEY}
      XMTP_CLIENT_PK: ${XMTP_CLIENT_PK}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      EXPRESS_HOST: ${EXPRESS_HOST}
      EXPRESS_PORT: ${EXPRESS_PORT}
      VIRTUAL_HOST: ${ROBOT_DOMAIN}
      VIRTUAL_PORT: ${EXPRESS_PORT}
  xmtp:
    image: "ghcr.io/relaycc/robot/xmtp:${GITHUB_SHA}"
    build:
      context: ".."
      dockerfile: "./deploy/Dockerfile.xmtp"
    environment:
      FRONT_API_KEY: ${FRONT_API_KEY}
      XMTP_CLIENT_PK: ${XMTP_CLIENT_PK}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      EXPRESS_HOST: ${EXPRESS_HOST}
      EXPRESS_PORT: ${EXPRESS_PORT}
      VIRTUAL_PORT: ${EXPRESS_PORT}
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro