version: "3.9"
services:
  express:
    image: "ghcr.io/relaycc/robot/express:${GITHUB_SHA}"
    build:
      context: "./typescript"
      dockerfile: "./docker/app.express.Dockerfile"
    expose:
      - ${EXPRESS_PORT}
    environment:
      FRONT_API_KEY: ${FRONT_API_KEY}
      XMTP_CLIENT_PK: ${XMTP_CLIENT_PK}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      EXPRESS_HOST: ${EXPRESS_HOST}
      EXPRESS_PORT: ${EXPRESS_PORT}
      VIRTUAL_HOST: ${ROBOT_DOMAIN}
      LETSENCRYPT_HOST: ${ROBOT_DOMAIN}
      VIRTUAL_PORT: ${EXPRESS_PORT}
      ROBOT_DOMAIN: ${ROBOT_DOMAIN}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      GITHUB_SHA: ${GITHUB_SHA}
  xmtp:
    image: "ghcr.io/relaycc/robot/xmtp:${GITHUB_SHA}"
    build:
      context: "./typescript"
      dockerfile: "./docker/app.xmtp.Dockerfile"
    environment:
      FRONT_API_KEY: ${FRONT_API_KEY}
      XMTP_CLIENT_PK: ${XMTP_CLIENT_PK}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      EXPRESS_HOST: ${EXPRESS_HOST}
      EXPRESS_PORT: ${EXPRESS_PORT}
      VIRTUAL_PORT: ${EXPRESS_PORT}
      ROBOT_DOMAIN: ${ROBOT_DOMAIN}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=achilles@relay.cc
      - DEBUG=1
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  conf:
  vhost:
  html:
  certs:
  acme: