version: "3.9"
services:
  monitor:
    image: "robot-monitor"
    build:
      context: "./typescript"
      dockerfile: "./docker/monitor.Dockerfile"
    expose:
      - ${EXPRESS_PORT}
    environment:
      EXPRESS_HOST: ${EXPRESS_HOST}
      EXPRESS_PORT: ${EXPRESS_PORT}
      ROBOT_DOMAIN: ${ROBOT_DOMAIN}
      MONITOR_HEARTBEAT_DOMAIN: ${MONITOR_HEARTBEAT_DOMAIN}
      MONITOR_DISCORD_TOKEN: ${MONITOR_DISCORD_TOKEN}
      MONITOR_DISCORD_CHANNEL_ID: ${MONITOR_DISCORD_CHANNEL_ID}
      MONITOR_ROBOT_XMTP_ADDRESS: ${MONITOR_ROBOT_XMTP_ADDRESS}
      MONITOR_XMTP_PK: ${MONITOR_XMTP_PK}
      MONITOR_RESPONDER_ID: ${MONITOR_RESPONDER_ID}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}