version: "3.9"
services:
  robot-server:
    image: "robot-server"
    build:
      context: ".."
      dockerfile: "./ci/Dockerfile.express"
    expose:
      - 9000:9000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local
